fix: skeleton now generates without a panic
TheButlah/ferrous_slimevr pull request #1
Opened 2022-06-12 04:10 UTC by ZigTag

Allows the skeleton code to properly compile, refactors g.add_node(...).add_bone(...) to a more simplified g.add_child(...), also adds a test which serves as an example to how the skeleton is supposed to be initialized

2022-06-12 20:12 UTC, TheButlah requested changes
Thanks for the contribution, I really appreciate it! Especially tests, tests are good ♥️

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/tests/integration_test.rs
> +fn skeleton_test() {
rename to `test_lengths`

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/tests/integration_test.rs
> +    assert_eq!(skeleton[BoneKind::FootL].length(), 4.);
Could you write a loop that tests each bone? You can iterate over all possible bones with `bone_lengths.iter()`

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/tests/integration_test.rs
> +// A minor example showing how the code is supposed to work
```suggestion
/// Tests that all lengths of the skeleton are properly initialized based on `SkeletonConfig`
```

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +            let child = g.add_child(
```suggestion
            let (edge, _tail) = g.add_child(
```

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +            bone_map[BoneKind::Neck] = Some(child.0);
```suggestion
            bone_map[BoneKind::Neck] = Some(edge);
```

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
>                  let child_kind = child_kind.to_owned();
```suggestion
                let child_kind = *child_kind;
```

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +                let child = g.add_child(
```suggestion
                let (edge, _tail) = g.add_child(
```

2022-06-12 20:12 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +                bone_map[child_kind] = Some(child.0);
```suggestion
                bone_map[child_kind] = Some(edge);
```

2022-06-12 20:14 UTC, TheButlah commented
The code will fail the tests due to the failing test in `conventions`, but assuming all other tests pass I will override that and merge once the other requests for changes are addressed

2022-06-13 22:53 UTC, TheButlah commented
@ZigTag please don't mark conversations as resolved, the reviewer should do that

2022-06-13 22:57 UTC, TheButlah requested changes

2022-06-13 22:57 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +/// Used to initialize the [`Skeleton`](crate::skeleton::Skeleton) with its initial parameters
```suggestion
/// Used to initialize the [`Skeleton`] with its initial parameters
```

2022-06-13 22:57 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +            assert_eq!(&skeleton[i].length(), j);
```suggestion
        for (bone, length) in bone_lengths.iter() {
            assert_eq!(&skeleton[bone].length(), length);
```

2022-06-13 22:57 UTC, TheButlah commented on skeletal_model/src/skeleton.rs
> +    use crate::Skeleton;
```suggestion
    use super::*;
```

2022-06-13 23:20 UTC, ZigTag commented
> @ZigTag please don't mark conversations as resolved, the reviewer should do that. Makes it harder for me to incrementally review

My apologies, im used to using it as a checklist.

2022-06-14 07:48 UTC, merged

2022-06-14 07:48 UTC, TheButlah commented
Thanks for the contribution!